Azure/aks-periscope

pkg/exporter/azureblob_exporter.go

Private cluster fqdn format is `*.UUID.privatelink.<region-name>.azmk8s.io`, use first 63 char as container name.

Fix FQDN length issues for private cluster

---

pkg/exporter/azureblob_exporter.go

This fixes the trailing dash `-` in storage name issue. Associated with https://github.com/Azure/aks-periscope/pull/20 
* Its kind of undocumented, but some pseudo mention here: https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names 
cc: @feiskyer and @JunSun17

Storage name starting and ending with "-" is invalid name.

---

deployment/aks-periscope.yaml

This is prep for adding `acr image = v03` to yaml for the private cluster fix to encorporate with `latest` tag.
Once merged, we will add `tag 3` for this version and make sit `latest` tag to this commit. Hence `az-cli` will use the latest.
I have test this with the `jumpbox`, looks good.

Add v0.3 acr image for Private cluster fix.

---

README.md

Intent of this PR are as follows: 
* To add more direct local repo building information.
* To locally test this with local version of `docker hub` etc.
Please feel free to add more as comments, or ping me directly (whatever suites): 
* I have also refined and removed whole lot information from the [deleted guide here](https://github.com/Azure/aks-periscope/commit/688032aa68f0a93c30f166eceb29a9fb3bf61d58#diff-fa905989049ceb9dc9abe08d545c9857181e8b26295065bdb355be75c928bfea).

Add local build and test publish mechanism as programming guide.

---

tests/aksperiscopeintegration_test.go

CI test failing, because of missing `strings` import.
So first clear advantage of adding tests. Thanks.
* Successful test run here for CI : https://github.com/Azure/aks-periscope/pull/40/checks?check_run_id=2267294923 
/hallpass so that I can get the build to green.

Adding missing strings import.

---

deployment/aks-periscope.yaml
deployment/cluster-role-binding.yaml
deployment/cluster-role.yaml
deployment/config-map.yaml
deployment/crd.yaml
deployment/daemon-set.yaml
deployment/examples/kustomization_storage_account.yaml
deployment/kustomization.yaml
deployment/namespace.yaml
deployment/service-account.yaml
docs/kustomize.md

Deploy with Kustomize

---

cmd/aks-periscope/aks-periscope.go
deployment/aks-periscope.yaml
pkg/collector/collector.go
pkg/collector/osm_collector.go
pkg/utils/helper.go

This PR adds collectors for [OSM](https://github.com/openservicemesh/osm) and [SMI](https://smi-spec.io/). SMI collector can be broken out into a separate PR as well.
* Flags: in `aks-periscope.yaml`, setting flags to `OSM` turns on both osm and smi collectors. `SMI` flag turns on just smi collector
* `osm_collector` collects the following for each Open Service Mesh present on the cluster:
* ground truth - list/configs of all resources and mutating and validating webhook configurations
* for each osm control plan namespace - pod configs and logs of OSM controller and OSM injector pods
* for each namespace monitored by osm: metadata, services, endpoints, service accounts, configmaps, etc.
* [moving this into a separate PR] `smi_collector` collects the traffic targets, traffic splits, …

feat: add OSM logs collector

---

.github/workflows/ci-pipeline.yml

There was a code refactor PR which got rid of a buggy behaviour which caused the test to fail for obvious reasons.
This test fix is more true to its correct behaviour rightnow.
Previous behaviour: if user reply periscope with validation as false, oi.e. no storage in play, it will still go and run the pods under the hood.
Note: We cannot emulate storage hence as an end to end earlier, we were piggy backing on a bug which was hdden on the aks-periscope, which had a pod running even with the validation=false

fix test according to non-buggy behaviour.

---

deployment/aks-periscope.yaml

We need to fix the current `master` yaml which is consumed in vscode directly.
* https://github.com/Azure/aks-periscope/pull/65/files#diff-cabcaac1a231e2d530ba374ca786e837a4c7f802f98c86299b93874aaf2e78eaL95 
This opens up and I think we can now start thinking after next release to have cleaner release for customise transition. 
cc: @arnaud-tincelin , thanks

Fix for vscode consuming old image with new yaml changes.

---

.dockerignore
builder/Dockerfile
deployment/daemon-set.yaml

- cleanup dockerfile & use `ENTRYPOINT`
- fix mount paths

Dockerfile cleanup & fix deployment

---

pkg/utils/helper.go
tests/helper_test.go

This PR intends to Fix the multiple `GetHostName` calls to Singleton call using `Sync.Once.Do`
This PR also try to attempt and simplify the deep parameter passing mechanism. Why using `Sync.Once` because its a thread safe go existing pkg funct which we can use.  https://pkg.go.dev/sync#Once .
Please note: feel free to add your variable naming preferences but this way will ensure that the call for the actual `run command` only happens once. **Advantage** of this approach is that all changes reside under `utils` umbrella, no extra func parameter will be required, and it will guarantee the actual code is ran only once. 
Another, pro is that the call to the method stays same, under the hood it only gets called once. For future any new diagnostics or anything which needs to call the …

Singleton implementation for GetHostName.

---

deployment/aks-periscope.yaml

This is prep for adding acr image = v0.4 to yaml for list of fixes for 34 small to medium size workitems [release here](https://github.com/Azure/aks-periscope/releases/tag/untagged-c60b581a606b7a6453f4).
Once merged, we will add tag v0.4 for this version and make sit latest tag to this commit. Hence az-cli will use the latest as well and with master change vscode will use latest as well.
Thanks heaps,
@JunSun17 , @arnaud-tincelin , @qpetraroia , and @rzhang628 Thanks heaps 🙏

Add v0.4 image to new release.

---

pkg/collector/dns_collector.go
pkg/collector/dns_collector_test.go

This is the work for ARC for log level error visibility in case od DNS logs than pods level error visibility.
Thanks,
* Test image : `docker.io/tatsat/dns-logs-visibility` 
Thank you guys ☕️  : @arnaud-tincelin , @sophsoph321 and @safeermohammed

dns logs will contain error rather than actual pod error visibility.

---

deployment/cluster-role.yaml
go.mod
pkg/collector/osm_collector.go
pkg/collector/osm_collector_test.go
pkg/collector/smi_collector.go

- Updates to collect osm custom resource meshconfig per latest osm release
- Fixes collection of smi crds (rbac in cluster-role)
- Adds naming structure to filename: `meshName/resourceName_resourceType` and `smi/resourceName_resourceType>`
- Tested with kustomize `kubectl apply -k deployment`

osm/smi: update dir structure and add test

---

cmd/aks-periscope/aks-periscope.go
pkg/collector/pdb_collector.go
pkg/collector/pdb_collector_test.go

This implementation is to collect the information which usually help folks for identification of Pod disruption budget related glitches.
This PR should take care of #134 , cc: @SriHarsha001 as he is aware of these logic essentially this is just raw collection of data which could help in identification of PDB related issues. Plus @bcho 
Thanks. 🙏

add pod distribution budget information collector.

---

cmd/aks-periscope/aks-periscope.go
pkg/diagnoser/networkconfig_diagnoser.go
pkg/diagnoser/networkoutbound_diagnoser.go
pkg/utils/helper.go

This PR is important for 2 reasons:
* This pull request removes leftover kubectl dependencies and the only leftovers are the `OSM` and `SMI` collectors only.
* This pull request moves the repo more closer to a goal of stop using the `kubectl` command and use `client-go` module instead.
The work also redo the `creationTime` fetch and removes bunch of stuff which seems like unnecessary and not in need, I will ping JunSUn to take a look but I have tested this agains the vanilla `AKS Cluster` and seems to be behaving fine.
* Test image: `docker.io/tatsat/misc-move-to-client-go` 
Thanks,
cc: @rzhang628 , @arnaud-tincelin, @JunSun17 , @sophsoph321 , plus @bcho ❤️🙏☕️

Use client-go and remove unecessary kubectl.

---

.github/workflows/ci-pipeline.yaml
pkg/collector/nodelogs_collector.go
pkg/collector/nodelogs_collector_test.go

Addresses #158 - this creates a new key for each log file (sanitized by replacing '/' with '_') rather than writing every file to the same key.

Fix Node Logs Collector to use separate keys for each log file

---

cmd/aks-periscope/aks-periscope.go
pkg/collector/osm_collector.go
pkg/collector/osm_collector_test.go
pkg/utils/kubeCommandRunner.go

Addresses #124 
This is to take us one step further towards removing our reliance on the `kubectl` binary and parity between operating systems.
Since almost all the data we collect for OSM and SMI is JSON/YAML/tables, we don't really want or need the strongly-typed kubernetes resource types provided by the client-go library. Instead we use the `Unstructured` package which allows relatively trivial serialization to these formats.
Much of the code that replicates the output of `kubectl` commands is common between OSM and SMI collectors, and has been refactored out into the shared `KubeCommandRunner` type.

Use client-go for OSM collector

---

README.md

Make it clear in the README that the kustomize deployment requires kubectl 1.21 or later.
See #184 and #189

Add note to readme about kubectl version

---

.github/workflows/build-publish-mcr.yml

This PR is to add the automation of release tag generation when MCR gets published, so all manual work should be now automatic.
Please note: 
* I think currently we used to generate release tag with `v*.*.*` which will be now without `v` in front I feel it is for good because the image never has `v` as well.
Please feel free to add any further idea/thoughts.
So all we need to do is following:
* Create release PR with Changelog.md file and then after that gets merged.
* Click - `Publish mcr` action, which will look at Changelog, create release tag before mar release. (That is it :shipit: 🎊)
thank you so much, cc: @peterbom and @rzhang628 🙏☕️❤️🥷

Add automatic release tag generation.

---

README.md
deployment/overlays/dev/README.md
deployment/overlays/dynamic-image/README.md
deployment/overlays/dynamic-image/kustomization.template.yaml

This attempts to address some shortcomings in the READMEs for deploying Periscope using external image registries.
Thanks to @bravebeaver for pointing out that you can use the `az aks update --attach-acr` command to link an AKS cluster to an ACR.
Being able to use ACR is really handy because it allows us to publish and test images from a local filesystem (without needing to push to GitHub).
Even when it's not possible to use the `attach-acr` approach (which requires subscription `Owner` role assignment), you can still deploy a secret containing ACR credentials, so that approach is also described here.

Update deployment notes for image registries to include ACR as well as GHCR

---

README.md
deployment/overlays/dev/README.md
deployment/overlays/dynamic-image/README.md
docs/appendix.md

We are currently advising users to generate a SAS containing permissions for unused or invalid [operation parameters](https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specify-the-account-sas-parameters):
- 'd' (delete): not used - we are not deleting any containers or blobs
- 'u' (update): invalid - only for queue messages and table entities
- 'p' (process): invalid - only for queue messages
Also, the SAS generation examples using as CLI are not consistent with the main README.
This updates both, so that the remaining operations are: read, list, add (append blob), create and write.

Remove unnecessary permissions in documentation for SAS generation

---

builder/Dockerfile.linux

This fixes a bug introduced with the recent change to use distroless images, which don't contain the `nsenter` binary. This utility is still required to run processes on the host VM, and is used by the `iptables`, kubelet-command and system-logs collectors, and so those collectors are currently failing.
Note: Windows images are unaffected, since they never relied on `nsenter` and those collectors are disabled on Windows.

Add nsenter to Linux Periscope image

---

deployment/base/daemon-set.yaml
deployment/components/win-hpc/CollectDiagnostics.ps1
deployment/components/win-hpc/daemon-set.yaml

This addresses #219.
The values are based on the actual pod memory (from metrics server) on an AKS cluster (incorporating a buffer to allow for some future extra memory usage or clusters where there is more data to process).
The Windows 'diagnostics collection' DaemonSet did not already have a resources block, so this is added here. The numbers are extremely high for this because the PowerShell script that does the log collection is very memory-hungry when compressing events into a zip file.
This also fixes a minor bug in the Windows log collection script that would occasionally result in it running without a `run_id` value when Periscope was repeatedly deployed to the same cluster without deletion.

Update resource requests and limits for all Periscope pods

---

.github/dependabot.yml

Updating all k8s.io dependencies in a single PR should reduce the chance of build errors resulting from incompatibilities when upgrading to later versions. It should also minimize the number of PRs we need to review and merge.
Relates to #234

Group k8s.io dependencies so that dependabot updates them in one go
